### ISSUE TITLE
the code stuck in prediction step.

### ISSUE THREAD

**Issue by h2222** [luyug/Reranker#2]
hi author, I try to run your prediction step by using commend :
```
 python -m torch.distributed.launch --nproc_per_node 4 python run_marco.py \
  --output_dir {score saving directory, not used for the moment} \
  --model_name_or_path {path to checkpoint} \
  --tokenizer_name bert-base-uncased \
  --do_predict \
  --max_len 512 \
  --fp16 \
  --per_device_eval_batch_size 64 \
  --dataloader_num_workers 8 \
  --pred_path {path to prediction json} \
  --pred_id_file  {path to prediction id tsv} \
  --rank_score_path {save path of the text file of scores}
```
but the program just stuck in someplace like what the picture shows:
![image](https://user-images.githubusercontent.com/41234638/115346967-6ccdb200-a1e3-11eb-85ad-9a199ea511e3.png)

I also checked the GPU status by using commend `nvidia-smi`, the result shows that 3 cards are running for this program.
![image](https://user-images.githubusercontent.com/41234638/115347559-22006a00-a1e4-11eb-95f3-b4f89056a678.png)

I am waiting for very long time that still can not run to the next step,  it is normal or how can I fix that?

thanks.

**Comment by luyug** [comment]
This is not normal.

Your error message suggests that this is an infiniband issue. Nvidia-smi is showing 3 cards busy waiting the fourth.

Please check your environment and/or network connection. I also suggest run `export NCCL_DEBUG=INFO` or `export NCCL_DEBUG=DEBUG` to see if this is an NCCL problem.

**Comment by h2222** [comment]
> This is not normal.
> 
> Your error message suggests that this is an infiniband issue. Nvidia-smi is showing 3 cards busy waiting the fourth.
> 
> Please check your environment and/or network connection. I also suggest run `export NCCL_DEBUG=INFO` or `export NCCL_DEBUG=DEBUG` to see if this is an NCCL problem.
Hi author
thanks for your mind, the problem is fixed by simply replace `--nproc_per_node 4` to `--nproc_per_node 3`
thanks a lot!
