### ISSUE TITLE
DDP support

### ISSUE THREAD

**Issue by mylcode** [luyug/Reranker#3]
Hi @luyug, thanks for opening source this repo.  

I checked the repo for DDP support, which I didn't find codes related to dist.init_process_group or ddp model wrapper, though there is distributed sampler. you mentioned ddp training is supported in readme, do you include codes of that part? or there is sth I  need to learn under the hood?

Thanks

**Comment by luyug** [comment]
Our trainer is a sub class of huggingface trainer, and similarly the training argument a sub class of hugging face training argument. They define the DDP routines.

**Comment by mylcode** [comment]
Thanks for the prompt reponse.  This is interesting, it's even don't need to assign args in cmd line.

**Comment by mylcode** [comment]
My bad, indeed there is DPP invoke in cmd line:

python **-m torch.distributed.launch --nproc_per_node 4** run_marco.py \
  --output_dir {directory to save checkpoints} \
  --model_name_or_path  bert-base-uncased \
  --do_train \
  --save_steps 2000 \
  --train_dir {path to a train json splits from last step} \
  --max_len 512 \
  --fp16 \
  --per_device_train_batch_size 1 \
  --train_group_size 8 \
  --gradient_accumulation_steps 1 \
  --per_device_eval_batch_size 64 \
  --warmup_ratio 0.1 \
  --weight_decay 0.01 \
  --learning_rate 1e-5 \
  --num_train_epochs 2 \
  --overwrite_output_dir \
  --dataloader_num_workers 8 \
